### ISSUE TITLE
Can possible to recognition  from own image

### ISSUE THREAD

**Issue by junoprima** [thebigpotatoe/node-red-contrib-face-recognition#11]
Hello i need a solution to recognition  my image  from  database e.g. i have 5 image name  Tony

and i use that 5 image recognition  from webcam image or another source image 

thank for help

**Comment by thebigpotatoe** [comment]
Boy is this node for you then,

Have a look at the [Readme](https://github.com/thebigpotatoe/node-red-contrib-face-recognition/blob/master/README.md),

Have a look online for [node red webcams](https://flows.nodered.org/node/node-red-contrib-node-webcam),

Have a look online for [how to read a file in node red](https://discourse.nodered.org/t/how-to-open-image-image-from-local-file-directory/11952),

Then smash it all together using the example.

Finally, I'm closing this since its not an issue,
