### ISSUE TITLE
bounding box coordinates

### ISSUE THREAD

**Issue by wifff** [thebigpotatoe/node-red-contrib-face-recognition#16]
Hi,
Healthy new year !
I installed node-red-contrib-face-recognition without problems on a Raspbery Pi4.

I found the bounding box surrounding  the facial landmarks: payload.face_recon.faces[0].alignedRect._box
But I would need the coordinated for the larger bounding box covering the whole face - (as shown in the preview (box with blue lines) 

Any help very appreciated !

Best regards,
Wolfgang

**Comment by thebigpotatoe** [comment]
I just built another app using Face-API.js, and tbh I'm not sure how he gets those co-ordinates, they just appear after using the inbuilt draw function. 

I have never used them personally in an use case so I haven't noticed the fact. All this node does is pass the info from face-api.js after inference to the node output so if the boxes don't line up that's from the base library.

 I haven't seen anything at the repo mention bounding box details, but I didn't dig deep. Maybe there is some useful info over there?

Otherwise maybe expand the current bounding box by like 20% or so?

**Comment by wifff** [comment]
Thanks a lot for the feedback. Expanding the bounding box of the  facial landmarks will solve the problem in most cases !
Best regards,
Wolfgang

**Comment by thebigpotatoe** [comment]
Awesome, glad I could help, I'm going to close the issue then.
