### ISSUE TITLE
How do you "see" who is whom in the pictures?

### ISSUE THREAD

**Issue by agoralive** [thebigpotatoe/node-red-contrib-face-recognition#8]
I now have this working using a windows computer, and that's strange in it's own way, BUT....

If I teach the node that Sheldon is actually Sheldon and Lennard is Lennard, the node "just" puts out information which leaves me with no clue what so ever.

Another test I did was, feed the flow with the picture I used for Sheldon as the descriptor, while passing this though with both Lennard and Sheldon as possible in the picture.

Does this make sence?

Picture-in of Sheldon - 2 possible candidates (Sheldon & Lennard) - Node puts out outcome for both possibilities :(

**Comment by thebigpotatoe** [comment]
This is my fault, I left the message output in weird state when I was trying to improve it. I also haven't written how it works anywhere  either. So this is on me.

If you explore the object that is output by the input nodes after a computation, there are a couple of key objects;

The first is the Matched Faces Array. This is a new feature, and is an array that holds the basic info on any matched faces found for your selected image from all used compute nodes. A matched face is one that matches a descriptor under the confidence value you have input. So for your example above, it should contain one entry for sheldon. If you make another compute node with a descriptor for lennard, he should also appear in this array.

The other objects output are the results of each compute node. Within each of these objects is information about how that compute node analysed the image. The faces array within this is of found faces critical info showing the results for all possible options that were selected and run over that faces in the image. Again for your example, this should contain 2 entries, one for sheldons face and one for lennards face. In sheldons entry it should say matched and give you the name, in lennards since it is not recognised it will just say unknown.

The last piece of useful info is the image buffer that is also output for each compute node. This is the labelled image from the compute node with all requested info drawn on the image. 

This is the part where I got stuck, and why the output is a little messy. I wanted to combine the image outputs of multiple compute nodes, however when using child processes, information is lost when passing back to the parent which prevents me from making one nice summarized image. This gave rise to the Matched Faces Array for the mean time.

Let me know if this makes sense

**Comment by agoralive** [comment]
Yes I do believe this helps, but a "simple" idea would be to be able to NAME the persons and have the node "just" write the name or names which is known by the learned faces in it's descriptor "database"

At the moment it is not "simple" enough to use for my setup, but thank you for your time and efforts in making this :)

**Comment by thebigpotatoe** [comment]
Thanks for the feedback :) 

The aim will be to make this as simple as possible when i understand how to do so in javascript. With all that's going on in the world I'm not sure when that will be. But keep an eye out on updates on this repo to see when I manage to figure it out.
